//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularioExcel.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiario
    {
        public int Id { get; set; }
        public Nullable<int> TrabajadorId { get; set; }
        public Nullable<int> TipoBeneficiario { get; set; }
        public Nullable<int> BeneficiarioTipoId { get; set; }
        public Nullable<int> BeneficiarioId { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public Nullable<int> IdParentesco { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> IdGenero { get; set; }
    
        public virtual Trabajador Trabajador { get; set; }
    }
}
