//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularioExcel.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudades
    {
        public int Ciudad_Id { get; set; }
        public string Nombre { get; set; }
        public string Departamento { get; set; }
        public string EpsSucursalId { get; set; }
        public Nullable<int> CodDepartamento { get; set; }
        public Nullable<int> CodMunicipio { get; set; }
    }
}
