//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularioExcel.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conyuge
    {
        public int Id { get; set; }
        public Nullable<int> TrabajadorId { get; set; }
        public int TipoBeneficiario { get; set; }
        public int BeneficiarioTipoId { get; set; }
        public int BeneficiarioId { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int IdGenero { get; set; }
        public Nullable<DateTime> FechaIngresoEmpresa { get; set; }
        public Nullable<int> SalarioBasico { get; set; }
        public string TrabajaConyugue { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<int> Nit { get; set; }
        public string RecibeSub { get; set; }
        public string CajaSub { get; set; }
    
        public virtual Trabajador Trabajador { get; set; }
    }
}
