//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularioExcel.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleador
    {
        public int Id { get; set; }
        public Nullable<int> TrabajadorId { get; set; }
        public Nullable<int> TipoBeneficiario { get; set; }
        public Nullable<int> Tipo_Novedad { get; set; }
        public Nullable<DateTime> FechaRadicacion { get; set; }
        public Nullable<int> TipoIdentificacionEmpresa { get; set; }
        public Nullable<int> Nit { get; set; }
        public Nullable<int> DigitoVerificacion { get; set; }
        public string Nombre_RazonSocial { get; set; }
        public Nullable<int> Sector { get; set; }
        public string Sucursal { get; set; }
        public string Direccion { get; set; }
        public string Departamento { get; set; }
        public string Telefono { get; set; }
    
        public virtual Trabajador Trabajador { get; set; }
    }
}
