//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularioExcel.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        public int Id { get; set; }
        public int Nit { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Razon { get; set; }
        public Nullable<int> DV { get; set; }
    }
}
