//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularioExcel.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ColsubsidioEntities : DbContext
    {
        public ColsubsidioEntities()
            : base("name=ColsubsidioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beneficiario> Beneficiario { get; set; }
        public virtual DbSet<Ciudades> Ciudades { get; set; }
        public virtual DbSet<Conyuge> Conyuge { get; set; }
        public virtual DbSet<Empleador> Empleador { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
    }
}
