//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularioExcel.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajador()
        {
            this.Beneficiario = new HashSet<Beneficiario>();
            this.Conyuge = new HashSet<Conyuge>();
            this.Empleador = new HashSet<Empleador>();
        }
    
        public Nullable<int> TrabajadorId { get; set; }
        public int Id { get; set; }
        public int TipoBeneficiario { get; set; }
        public int trabajadorTipoId { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int IdGenero { get; set; }
        public Nullable<int> IdNacionalidad { get; set; }
        public int IdEstadoCivil { get; set; }
        public int IdNivelOcupacion { get; set; }
        public Nullable<int> IdNivelEducativo { get; set; }
        public System.DateTime FechaIngresoEmpresa { get; set; }
        public int HorasMes { get; set; }
        public Nullable<int> Trabajador1 { get; set; }
        public int SalarioBasico { get; set; }
        public string Celular { get; set; }
        public string EPS { get; set; }
        public string AFP { get; set; }
        public string Direccion_V { get; set; }
        public Nullable<int> Ciudad_V { get; set; }
        public Nullable<int> Dpto_V { get; set; }
        public int Zona_V { get; set; }
        public string Telefono_V { get; set; }
        public string Direccion_T { get; set; }
        public Nullable<int> Ciudad_T { get; set; }
        public Nullable<int> Dpto_T { get; set; }
        public Nullable<int> Zona_T { get; set; }
        public string Telefono_T { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beneficiario> Beneficiario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conyuge> Conyuge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleador> Empleador { get; set; }
    }
}
